### ISSUE TITLE
SUGERENCIA: COLOCAR TIEMPO A CADA PREGUNTA.

### ISSUE THREAD

**Issue by Fabrizio1996laz** [nancysanchezuno/trivianancy#1]
Sugiero que coloques un tiempo por pregunta

**Comment by nancysanchezuno** [comment]
Gracias por la sugerencia, había colocado 1 segundo de espera por pregunta, ahora la espera se extendió a 3 segundos.

**Comment by Fabrizio1996laz** [comment]
Genial !! Lo he probado y te a quedado bien .
