### ISSUE TITLE
AUMENTAR MAS PREGUNTAS EN LA TRIVIA.

### ISSUE THREAD

**Issue by Fabrizio1996laz** [nancysanchezuno/trivianancy#2]
Buenas tardes Nancy tengo una observación,
cuando acaba la trivia indica si se desea duplicar tus puntos, considero que se debe realizar una pregunta más donde si le va bien se duplique los puntos , caso contrario se mantenga sus puntos como están.

![foto1](https://user-images.githubusercontent.com/113265534/190874696-c448149c-c797-4053-bdba-35ba0a978579.JPG)

**Comment by nancysanchezuno** [comment]
Muchas gracias por tu observación Fabrizio, pero no podría duplicarse los puntos si le va bien, así como no se debería dividir los puntos si le va mal al jugador, debido a que estos resultados muestran fehacientemente cuanto se conoce del tema y cuánto se ha esforzado el jugador. 

Lo que sí hice en la parte final de mi trivia  fue añadir una RULETA DE LA SUERTE muy divertida, donde el jugador de manera opcional prueba su "suerte".

**Comment by Fabrizio1996laz** [comment]
Hola Nancy, correcto la trivia te quedo genial. !!
