### ISSUE TITLE
VALIDAR NOMBRE

### ISSUE THREAD

**Issue by Fabrizio1996laz** [nancysanchezuno/trivianancy#3]
Hola Nancy tengo una observación ,
si no le pones nombres la trivia igualmente funciona.
![image](https://user-images.githubusercontent.com/113265534/190874890-166b832e-562c-4263-adc5-b7cba43b4bdb.png)

**Comment by nancysanchezuno** [comment]
Hola Fabrizio,mucha sgracias por tu sugerencia. Al realizar mi trivia quería que fuera personalizada y entretenida para el jugador,por ese motivo incluí la pregunta sobre los nombres y además añadí respuestas personalizadas. Lo excelente de las trivias es que podemos hacerlos lúdicos y dinámicos.

**Comment by Fabrizio1996laz** [comment]
Si me gusto mucho tu trivia. !!
